baseURL: '/'
languageCode: en-us
title: Aether's Vi 
theme: PaperMod
author: Zan Aether

params:
  socialIcons:
    - name: twitter
      url: https://twitter.com/aethernotfound
    - name: github
      url: https://github.com/juandma0

  comments: true
  
  
  
  
  cover:
    linkFullImages: true

  ShowBreadcrumbs: true

  ShowShareButtons: true



menu:
  main:
    # Categories
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 10
    # Tags
    - identifier: tags
      name: Tags
      url: /Tags/
      weight: 20
      
      
      



