baseURL: '/'
languageCode: en-us
title: Aether's Vi 
theme: PaperMod

outputs: # I don't know what this does
  home:
    - HTML
    - RSS
    - JSON


params:
  # Favicon
  assets:
    favicon: '/static/favicon.ico'
    favicon16x16: '/static/favicon-16x16.png'
    favicon32x32: '/static/favicon-32x32.png'
    apple_touch_icon: '/static/apple-touch-icon.png'
    safari_pinned_tab: '/static/apple-touch-icon.png'
  

  # Show Rss Button
  ShowRssButtonInSectionTermList: true

  # Disable summary
  hideSummary: true
  
  # Disable special card appearance
  disableSpecial1stPost: true

  # Enable social-metadata and SEO
  env: production

  # Enable comments
  comments: true

  # Home info content. Required for social media icons to show
  homeInfoParams:
    Title: Greetings. I'm Aether.    
    Content: I'm a Junior Software Developer who's learning every day to become a senior. Here you will find tutorials, posts, complaints, insight on some topics, and an overview of my learning.
  

  # Social icons
  socialIcons:
    - name: twitter
      url: https://twitter.com/aethernotfound
    - name: github    
      url: https://github.com/juandma0
    - name: rss
      url: /index.xml
    
  # Authors of the site
  author: ['Aether']
  

  # Code copy button
  ShowCodeCopyBUttons: true
  
  ShowToc: true
  
  # Post covers
  cover:
    linkFullImages: true

  # Breadcrumbs
  ShowBreadcrumbs: true

  # Social media share buttons
  ShowShareButtons: true


  fuseOpts: # I don't know what this does
      isCaseSensitive: false
      shouldSort: true
      location: 0
      distance: 1000
      threshold: 0.4
      minMatchCharLength: 0
      keys: ["title", "permalink", "summary", "content"]





menu:
  main:
 
    # Archives page
    - identifier: archives 
      name: Archives
      url: /archives/
      weight: 10

    # Search bar
    - identifier: search 
      name: Search 
      url: /search/
      weight: 20

    # Categories
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 30
    
    # Tags
    - identifier: tags
      name: Tags
      url: /Tags/
      weight: 40
      
      



